### ISSUE TITLE
Request body not present in ErrorHandlingMiddleware

### ISSUE THREAD

**Issue by vdwanderley** [lfmundim/Blip.Api.Template.K8s#15]
HttpContext request body is empty when a response passes throught ErrorHandlingMiddleware. Applying Request.EnableBuffering at the invoke method doesn't work probably because the body is already cleaned.

If the body really needs to be caught and logged, it's possible to add a middleware before ErrorHandlingMiddleware setting ErrorHandlingMiddleware and storing in memory so it can be read in a further moment by other middlewares.

**Comment by lfmundim** [comment]
The fix will be available on v1.7.1 in a few minutes

**Comment by cesarjrccorreia** [comment]
After update ErrorHandlingMiddleware in my api, when I request any endpoint the api crash and return "Cannot access a closed Stream".

**Comment by vdwanderley** [comment]
Stream must be left opened, something like this:
var reader = new StreamReader(stream, null, true, 1024, true)
although I'm not sure about how it might impact the application

**Comment by lfmundim** [comment]
Hotfixed on v1.7.2, should go live in a few minutes. v1.7.1 delisted
